<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Sweta-PC" failures="2" tests="2" name="LoginTests" time="7.26" errors="0" timestamp="2024-10-12T13:58:18 IST">
  <testcase classname="com.crm.qa.tests.LoginPageTests" name="loginPage_loginWithValidCred_Success" time="2.505">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.crm.qa.tests.LoginPageTests.loginPage_loginWithValidCred_Success(LoginPageTests.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginPage_loginWithValidCred_Success -->
  <testcase classname="com.crm.qa.tests.LoginPageTests" name="loginPage_loginWithValidCred_Success" time="7.239">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because &amp;quot;com.crm.qa.utils.TestListener.extentTest&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "com.crm.qa.utils.TestListener.extentTest" is null
at com.crm.qa.utils.TestListener.onTestFailure(TestListener.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginPage_loginWithValidCred_Success -->
  <testcase classname="com.crm.qa.base.TestBase" name="@BeforeSuite beforeSuiteSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuiteSetup -->
  <testcase classname="com.crm.qa.base.TestBase" name="@AfterSuite afterSuiteTearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuiteTearDown -->
</testsuite> <!-- LoginTests -->
